services:
  app:
#    image: ${IMAGE_NAME}:${IMAGE_VERSION}-perf-app
#    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: perf-app-srvc
    build:
      context: ./
      dockerfile: ./Dockerfile
#      cache_from:
#        - ${IMAGE_NAME}:${IMAGE_VERSION}-perf-app
#        - perf-app
    deploy:
      resources:
        limits:
          memory: 160M
    restart: unless-stopped
    ports:
      - 5110:5000