{
 "title": "PerfService",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Perf Srvc Runs count - rate intrvl - Play Bowling",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(PerfService_Runs_count{action=\"PerfRunner.Tests.PlayBowling\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Perf Srvc Runs count - rate intrvl - Play Login",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(PerfService_Runs_count{action=\"PerfRunner.Tests.Login\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Perf Srvc Runs count - rate intrvl",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(PerfService_Runs_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "PerfService Runs bucket - Hist",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(PerfService_Runs_bucket[$__rate_interval])))"
    }
   ]
  }
 ]
}